apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-demo
  name: dotnet-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-demo
  template:
    metadata:
      labels:
        app: dotnet-demo
    spec:
      containers:
      - image: fjb4/dotnet-demo-buildpacks
        name: dotnet-demo-buildpacks
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
