apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-demo
  name: python-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-demo
    spec:
      containers:
      - image: fjb4/python-demo
        name: python-demo
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        env:
        - name: PORT 
          value: '5000'
        - name: POD_NAME 
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
