apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-demo
  name: python-demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-demo
  type: LoadBalancer
status:
  loadBalancer: {}
